const sampleListings = [
  {
    title: "Charming Countryside B&B",
    description: "Enjoy a peaceful stay at this charming bed and breakfast surrounded by rolling hills.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1mYbxV-QkFJG3h1PGaJpAvSeFvotdoONW-w&s",
      filename: "Listingimage",
    },
    price: 700,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Modern Loft in the City",
    description: "Experience the heart of downtown from this stylish and modern loft.",
    image: {
      url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 1200,
    location: "New York City",
    country: "USA",
  },
  {
    title: "Beachfront Paradise",
    description: "Wake up to the sound of waves in this stunning beachfront villa.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh5AZi-tL7bieNpi_2MWNYE6G9hkoQQS4sRg&s",
      filename: "Listingimage",
    },
    price: 2000,
    location: "Maui",
    country: "USA",
  },
  {
    title: "Cozy Lakeside Cabin",
    description: "Relax by the lake in this cozy and secluded cabin retreat.",
    image: {
      url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 500,
    location: "Lake Tahoe",
    country: "USA",
  },
  {
    title: "Historic City Apartment",
    description: "Live like a local in this historic apartment in the heart of the city.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLDBv1UeEtQlGN_MkUiXprd5ktTjOW2k7pRA&s",
      filename: "Listingimage",
    },
    price: 850,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Snowy Mountain Lodge",
        description: "Escape to a cozy lodge with stunning snowy mountain views.",
    image: {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 950,
    location: "Aspen",
    country: "USA",
  },
  {
    title: "Tropical Treehouse Escape",
    description: "Reconnect with nature in this elevated tropical treehouse.",
    image: {
      url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 650,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Urban Minimalist Studio",
    description: "A sleek and minimalist studio perfect for solo travelers.",
    image: {
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 600,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Rustic Vineyard Cottage",
    description: "Stay in a cozy cottage surrounded by vineyards and hills.",
    image: {
      url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 750,
    location: "Napa Valley",
    country: "USA",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet.",
    image: {
      url: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 1100,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Secluded Desert Retreat",
    description: "Find peace in the quiet beauty of this desert hideaway.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHugrdNJlzvBT9KT0sCANAv-G9b05JkOXHHw&s",
      filename: "Listingimage",
    },
    price: 700,
    location: "Joshua Tree",
    country: "USA",
  },
  {
    title: "Elegant Paris Flat",
    description: "An elegant flat with a balcony overlooking the Eiffel Tower.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpkpgmj52q1tiNNf-o5NBHoPXEp4L6bNor-A&s",
      filename: "Listingimage",
    },
    price: 1400,
    location: "Paris",
    country: "France",
  },
  {
    title: "Modern Seaside Apartment",
    description: "Enjoy sea breezes from this stylish seaside apartment.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHugrdNJlzvBT9KT0sCANAv-G9b05JkOXHHw&s",
      filename: "Listingimage",
    },
    price: 950,
    location: "Nice",
    country: "France",
  },
  {
    title: "Jungle Eco Lodge",
    description: "Stay off-grid in this eco-lodge deep in the jungle.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDUPHBHx9iBDatZSv36eawp6Ebd-YNEyHg8A&s",
      filename: "Listingimage",
    },
    price: 500,
    location: "Amazon",
    country: "Brazil",
  },
  {
    title: "Bohemian Rooftop Studio",
    description: "A colorful and artsy studio with rooftop views.",
    image: {
      url: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&q=80&w=800",
      filename: "Listingimage",
    },
    price: 720,
    location: "Lisbon",
    country: "Portugal",
  },
  {
    title: "Lakeside Modern Retreat",
    description: "Recharge in style at this sleek lakeside retreat.",
    image: {
      url: "https://storage.needpix.com/rsynced_images/rome-2119840_1280.jpg",
      filename: "Listingimage",
    },
    price: 1000,
    location: "Queenstown",
    country: "New Zealand",
  },
  {
    title: "Classic London Townhouse",
    description: "Feel at home in this elegant townhouse near the city center.",
    image: {
      url: "https://c.pxhere.com/images/e8/44/9a76577e67272a52ab4e777cf47a-1635459.jpg!d",
      filename: "Listingimage",
    },
    price: 1250,
    location: "London",
    country: "UK",
  },
  {
    title: "Mediterranean Villa",
    description: "A luxurious villa with stunning ocean views and private pool.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIBl_fbT_sfN_E1NN6oxNV444KAeTA81OqDg&s",
      filename: "Listingimage",
    },
    price: 2200,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Tiny Home Experience",
    description: "Try minimal living in a fully equipped tiny home.",
    image: {
      url: "https://live.staticflickr.com/7585/26803652556_dd62a36399_b.jpg",
      filename: "Listingimage",
    },
    price: 480,
    location: "Portland",
    country: "USA",
  },
  {
    title: "Elegant Castle Stay",
    description: "Sleep like royalty in this restored European castle.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVUmnDp_UFykGAOXek--s_y_fcQmXTi6vNsw&s",
      filename: "Listingimage",
    },
    price: 1800,
    location: "Edinburgh",
    country: "Scotland",
  },
  {
    title: "Luxury Penthouse",
    description: "Stay in a modern penthouse with panoramic views of the city skyline.",
    image: {
      url: "https://storage.needpix.com/rsynced_images/dubai-2650364_1280.jpg",
      filename: "Listingimage",
    },
    price: 2500,
    location: "Dubai",
    country: "UAE",
  },
  {
    title: "Cottage in the Woods",
    description: "Escape to a secluded cottage surrounded by lush forest.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS269ISJ-sPpjNkXhp6Coz3M9m5kgjrw6rn9g&s",
      filename: "Listingimage",
    },
    price: 600,
    location: "Vermont",
    country: "USA",
  },
  {
    title: "Modern High-Rise Apartment",
    description: "Enjoy city life from this sleek high-rise apartment.",
    image: {
      url: "https://d3sftlgbtusmnv.cloudfront.net/blog/wp-content/uploads/2025/02/Milan-Cover-Photo-840x425.jpg",
      filename: "Listingimage",
    },
    price: 1400,
    location: "Hong Kong",
    country: "China",
  },
  {
    title: "Charming Parisian Flat",
    description: "Live like a local in this charming flat with views of Montmartre.",
    image: {
      url: "https://tripxl.com/blog/wp-content/uploads/2025/01/Prague-Castle.jpg",
      filename: "Listingimage",
    },
    price: 1300,
    location: "Paris",
    country: "France",
  },
  {
    title: "Seaside Villa",
    description: "Relax in this spacious villa with breathtaking ocean views.",
    image: {
      url: "https://storage.needpix.com/rsynced_images/forts-4088762_1280.jpg",
      filename: "Listingimage",
    },
    price: 1700,
    location: "Malibu",
    country: "USA",
  },
  {
    title: "Rustic Cabin in the Forest",
    description: "A cozy cabin retreat nestled in the forest for ultimate peace and privacy.",
    image: {
      url: "https://blog-img-dev.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2025/04/Places-To-Visit-In-San-Juan-Argentina-Cover-Image-840x425.jpg",
      filename: "Listingimage",
    },
    price: 550,
    location: "Oregon",
    country: "USA",
  },
  {
    title: "Stylish Beach House",
    description: "A modern beach house with floor-to-ceiling windows and a private pool.",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Places_to_Stay_in_Nainital_For_Honeymoon.png",
      filename: "Listingimage",
    },
    price: 1800,
    location: "Santa Monica",
    country: "USA",
  },
  {
    title: "Traditional Japanese Ryokan",
    description: "Immerse yourself in Japanese culture by staying at a traditional ryokan.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHyPT2OLeMNxw28toNC8L2skbLTL1m5o6LXg&s",
      filename: "Listingimage",
    },
    price: 900,
    location: "Kyoto",
    country: "Japan",
  },
  {
    title: "Contemporary Mountain House",
    description: "Live in luxury with stunning mountain views and modern amenities.",
    image: {
      url: "https://live.staticflickr.com/8007/7293617544_ea3fe84e8f_b.jpg",
      filename: "Listingimage",
    },
    price: 1600,
    location: "Whistler",
    country: "Canada",
  },
  {
    title: "Chic Studio in the Heart of the City",
    description: "A chic studio apartment with everything you need for a comfortable stay.",
    image: {
      url: "https://traveldudes.com/wp-content/uploads/2024/06/image-from-rawpixel-id-3343105-jpeg.jpg",
      filename: "Listingimage",
    },
    price: 750,
    location: "Berlin",
    country: "Germany",
  },
  {
    title: "Glamorous Desert Oasis",
    description: "A lavish retreat with a private pool and desert views.",
    image: {
      url: "https://img.atlasobscura.com/SpAMY1V7-nS7veengb_KxMy3u3e0yu1NqHYpOGRxiGE/rt:fit/w:600/c:5602:3735:nowe:0:7/q:81/sm:1/scp:1/ar:1/aHR0cHM6Ly9hdGxh/cy1kZXYuczMuYW1h/em9uYXdzLmNvbS91/cGxvYWRzL3BsYWNl/X2ltYWdlcy81NzY5/YTUwMi0wNTFiLTQ5/MjktYTZkNi1hZWM5/NTIzOTBlNDM3ZjNj/ZDFkNzZjNTQyZGNh/OWZfUm9jYV9kZWxf/ZWxlZmFudGUsX0hl/aW1hZXksX0lzbGFz/X1Zlc3RtYW4sX1N1/c3VybGFuZCxfSXNs/YW5kaWEsXzIwMTQt/MDgtMTcsX0REXzAz/Ny5qcGc.jpg",
      filename: "Listingimage",
    },
    price: 2000,
    location: "Phoenix",
    country: "USA",
  },
  {
    title: "Scenic Hilltop Mansion",
    description: "A luxurious mansion perched on a hill with sweeping views of the countryside.",
    image: {
      url: "https://www.ivisitiran.com/content/images/tourist_attractions/217/Bam-Citadel-4.jpg",
      filename: "Listingimage",
    },
    price: 3000,
    location: "Los Angeles",
    country: "USA",
  },
  {
    title: "Elegant Retreat in the Alps",
    description: "Escape to a stylish retreat in the heart of the Swiss Alps.",
    image: {
      url: "https://tripxl.com/blog/wp-content/uploads/2025/03/National-Library-Of-Kosovo.jpg",
      filename: "Listingimage",
    },
    price: 2200,
    location: "Interlaken",
    country: "Switzerland",
  },
  {
    title: "Luxury Safari Lodge",
    description: "Stay in a luxurious safari lodge surrounded by wildlife and nature.",
    image: {
      url: "https://greatruns.com/wp-content/uploads/2022/06/Ko-Samui-Cover.jpg",
      filename: "Listingimage",
    },
    price: 3500,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "Boutique Hotel in the Heart of the City",
    description: "Enjoy boutique luxury at this centrally located hotel.",
    image: {
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHugrdNJlzvBT9KT0sCANAv-G9b05JkOXHHw&s",
      filename: "Listingimage",
    },
    price: 1300,
    location: "Rome",
    country: "Italy",
  },
];

module.exports = { data: sampleListings };
